#!/bin/bash
# hush — one switch for quiet. Turns macOS Do Not Disturb on/off by pressing
# the symbolic hotkey nix-darwin declared (ID 175, ⌃⌥⇧⌘F13), sets/restores
# your Slack status, and runs any host hooks. The bar pill, the pounce
# palette command, and the CLI all drive this one script, so no two surfaces
# can ever disagree about what a toggle does.
#
# GENERATED by modules/hush/default.nix (@var@ substituted at build time).
set -uo pipefail

JQ="@jq@"
STATE_DIR="$HOME/.local/state/hush"
STATE_FILE="$STATE_DIR/state"
DB="$HOME/Library/DoNotDisturb/DB/Assertions.json"
SKETCHYBAR="/opt/homebrew/opt/sketchybar/bin/sketchybar"

# Must match the AppleSymbolicHotKeys 175 binding written by default.nix.
KEY_CODE=@keyCode@

SLACK_ENABLED=@slackEnabled@
SLACK_TOKEN_CMD=@slackTokenCommand@
SLACK_STATUS_TEXT=@slackStatusText@
SLACK_STATUS_EMOJI=@slackStatusEmoji@
SLACK_SNOOZE=@slackSnooze@
SLACK_SNOOZE_MINUTES=1440 # failsafe cap; unhush ends it earlier
HOOKS=(@hooks@)

# The stable-signed pounce copy (modules/pounce keeps its TCC grants alive
# across rebuilds). When it's new enough to have the `focus` subcommand, hush
# rides its Accessibility + Full Disk Access grants for the press AND the
# state read — one pair of checkboxes covers every surface. The probe greps
# --help because an OLDER pounce treats unknown args as ClientMode and would
# open the palette; never call `focus` unprobed.
POUNCE_SIGNED="$HOME/.local/state/pounce/Pounce.app/Contents/MacOS/pounce"
pounce_focus_available() {
    [ -x "$POUNCE_SIGNED" ] && "$POUNCE_SIGNED" --help 2>/dev/null | grep -q "focus status"
}

note() { printf 'hush: %s\n' "$*" >&2; }
notify() { /usr/bin/osascript -e "display notification \"$1\" with title \"hush\"" >/dev/null 2>&1 || true; }
poke_bar() { [ -x "$SKETCHYBAR" ] && "$SKETCHYBAR" --trigger hush_change >/dev/null 2>&1 || true; }

# on|off. Exact when the signed pounce can report it (its FDA grant) or when
# Assertions.json is readable directly (the calling app's own FDA); otherwise
# falls back to our own last write. Blind spots in fallback mode: toggles
# made from Control Center or another device.
focus_state() {
    local s db
    if pounce_focus_available; then
        s=$("$POUNCE_SIGNED" focus status 2>/dev/null) || s=""
        case "$s" in on | off)
            echo "$s"
            return
            ;;
        esac
    fi
    db=$(/bin/cat "$DB" 2>/dev/null || true)
    if [ -n "$db" ]; then
        if printf '%s' "$db" | "$JQ" -e '(.data[0].storeAssertionRecords // []) | length > 0' >/dev/null 2>&1; then
            echo on
        else
            echo off
        fi
        return
    fi
    /bin/cat "$STATE_FILE" 2>/dev/null || echo off
}

# Press the DND chord. Preferred: `pounce focus toggle` — since pounce 0.4.3
# the CLI forwards the press to the resident daemon whenever the calling
# context lacks the grant (TCC checks the RESPONSIBLE process — sketchybar
# for the pill, your terminal for the CLI — never the pounce binary itself),
# so the one Accessibility checkbox on the signed Pounce.app covers every
# surface. Fallback: System Events — only without a focus-capable pounce;
# then the keystroke is attributed to the app that invoked hush.
press_hotkey() {
    if pounce_focus_available && "$POUNCE_SIGNED" focus toggle 2>/dev/null; then
        return 0
    fi
    /usr/bin/osascript -e "tell application \"System Events\" to key code $KEY_CODE using {control down, option down, shift down, command down}" >/dev/null 2>&1
}

slack_token() { /bin/bash -c "$SLACK_TOKEN_CMD" 2>/dev/null || true; }

slack_api() { # $1 method, rest = curl args
    local method=$1
    shift
    /usr/bin/curl -sf --max-time 5 -H "Authorization: Bearer $TOK" "$@" \
        "https://slack.com/api/$method" 2>/dev/null
}

slack_set() { # $1 = on|off
    [ "$SLACK_ENABLED" = 1 ] || return 0
    TOK=$(slack_token)
    if [ -z "$TOK" ]; then
        note "slack: tokenCommand printed nothing — skipping (see 'hush doctor')"
        return 0
    fi
    local prev="$STATE_DIR/slack-prev.json"
    if [ "$1" = on ]; then
        # Stash whatever status was there so unhush can put it back.
        slack_api users.profile.get \
            | "$JQ" '{profile:{status_text:(.profile.status_text // ""), status_emoji:(.profile.status_emoji // ""), status_expiration:0}}' \
            >"$prev" 2>/dev/null || rm -f "$prev"
        local body
        body=$("$JQ" -n --arg t "$SLACK_STATUS_TEXT" --arg e "$SLACK_STATUS_EMOJI" \
            '{profile:{status_text:$t,status_emoji:$e,status_expiration:0}}')
        slack_api users.profile.set -H "Content-type: application/json; charset=utf-8" -d "$body" \
            | "$JQ" -e '.ok' >/dev/null || note "slack: users.profile.set failed"
        if [ "$SLACK_SNOOZE" = 1 ]; then
            slack_api dnd.setSnooze -d "num_minutes=$SLACK_SNOOZE_MINUTES" \
                | "$JQ" -e '.ok' >/dev/null || note "slack: dnd.setSnooze failed"
        fi
    else
        if [ -f "$prev" ]; then
            slack_api users.profile.set -H "Content-type: application/json; charset=utf-8" -d @"$prev" \
                | "$JQ" -e '.ok' >/dev/null || note "slack: status restore failed"
            rm -f "$prev"
        else
            slack_api users.profile.set -H "Content-type: application/json; charset=utf-8" \
                -d '{"profile":{"status_text":"","status_emoji":""}}' \
                | "$JQ" -e '.ok' >/dev/null || note "slack: status clear failed"
        fi
        if [ "$SLACK_SNOOZE" = 1 ]; then
            slack_api dnd.endSnooze -X POST | "$JQ" -e '.ok' >/dev/null || true
        fi
    fi
}

run_hooks() { # $1 = on|off
    local h
    for h in ${HOOKS[@]+"${HOOKS[@]}"}; do
        "$h" "$1" || note "hook failed (non-fatal): $h"
    done
}

apply() { # $1 = on|off
    local want=$1 cur
    cur=$(focus_state)
    if [ "$cur" != "$want" ]; then
        if ! press_hotkey; then
            note "keypress failed — the app invoking hush needs an Accessibility grant (run 'hush doctor')"
            notify "No Accessibility grant — run 'hush doctor' in a terminal"
            exit 1
        fi
    fi
    /bin/mkdir -p "$STATE_DIR"
    printf '%s\n' "$want" >"$STATE_FILE"
    slack_set "$want"
    run_hooks "$want"
    poke_bar
    note "$want"
}

doctor() {
    echo "hush doctor — the one-time setup, checked:"

    if pounce_focus_available; then
        echo "  [ok] signed pounce has the focus subcommand — hush rides its TCC grants"
        echo "       (grant Accessibility + Full Disk Access to Pounce.app once, done)"
    else
        echo "  [~~] no signed pounce with 'focus' — using the per-surface fallback"
        echo "       (needs a pounce with the focus subcommand + pounce.signingIdentity set)"
    fi

    if /usr/bin/defaults read com.apple.symbolichotkeys AppleSymbolicHotKeys 2>/dev/null \
        | grep -qE '^[[:space:]]*175[[:space:]]*='; then
        echo "  [ok] DND symbolic hotkey (175) is bound — nix re-asserts it every rebuild"
    else
        echo "  [!!] hotkey 175 not bound yet — run 'darwin-rebuild switch' (modules/hush binds it at activation)"
    fi

    if /bin/cat "$DB" >/dev/null 2>&1; then
        echo "  [ok] Focus state reads exact (Assertions.json reachable from this context)"
    else
        echo "  [~~] no Full Disk Access here → state falls back to hush's own memory and"
        echo "       can drift if you toggle Focus from Control Center or your phone."
        echo "       Fix: System Settings → Privacy & Security → Full Disk Access, add the"
        echo "       app that runs hush (your terminal for the CLI, sketchybar for the pill)."
    fi

    echo "  [??] Accessibility can't be probed without actually toggling. With the"
    echo "       signed pounce above, its daemon presses on behalf of every surface"
    echo "       (pill, palette, CLI) — the one grant on Pounce.app is enough."
    echo "       Without it, the app invoking hush needs its own grant (System"
    echo "       Settings → Privacy & Security → Accessibility)."

    if [ "$SLACK_ENABLED" = 1 ]; then
        TOK=$(slack_token)
        if [ -z "$TOK" ]; then
            echo "  [!!] slack: tokenCommand printed nothing — stash a token first, e.g."
            echo "       security add-generic-password -s hush-slack -a \$USER -w 'xoxp-…'"
        elif slack_api auth.test -X POST | "$JQ" -e '.ok' >/dev/null 2>&1; then
            echo "  [ok] slack: token accepted"
        else
            echo "  [!!] slack: API rejected the token (needs scopes users.profile:write + dnd:write)"
        fi
    else
        echo "  [--] slack: disabled (nebelhaus.hush.slack.enable)"
    fi
}

case "${1:-toggle}" in
    on) apply on ;;
    off) apply off ;;
    toggle) if [ "$(focus_state)" = on ]; then apply off; else apply on; fi ;;
    status) focus_state ;;
    doctor) doctor ;;
    *)
        echo "usage: hush [on|off|toggle|status|doctor]" >&2
        exit 64
        ;;
esac
