# nebelhaus.snippets — text expansion (espanso), the "@@" → email kind of thing.
#
# Why the Homebrew cask and NOT pkgs.espanso / services.espanso: macOS ties an
# Accessibility (TCC) grant to a stable, signed app identity. The home-manager
# services.espanso module runs the bare nix-store binary ($out/bin/espanso)
# under launchd, so every nixpkgs bump changes that path → the grant is orphaned
# → espanso relaunches, can't confirm Accessibility, and throws up its
# troubleshooting window on login. Running the signed /Applications/Espanso.app
# (cask) instead gives a stable path + Developer ID identity: grant it once and
# it survives reboots and updates — which is also what stops the startup window
# (that window was only ever the symptom of the missing grant).
{
  config,
  lib,
  username,
  ...
}:

let
  cfg = config.nebelhaus.snippets;

  # espanso reads YAML from ~/.config/espanso. Emit a readable match file from
  # the option; toJSON on each string does the quoting/escaping (so "@@",
  # embedded quotes, colons, and newlines all survive intact).
  matchLine = m: "  - trigger: ${builtins.toJSON m.trigger}\n    replace: ${builtins.toJSON m.replace}\n";
  matchesYaml =
    "# Generated by nebelhaus.snippets — edit the option, not this file.\nmatches:\n"
    + lib.concatMapStrings matchLine cfg.matches;

  # The cask's CLI lives inside the app bundle — a stable path with the app's
  # signed identity, which is the whole point (see the header).
  espanso = "/Applications/Espanso.app/Contents/MacOS/espanso";
in
lib.mkIf cfg.enable {
  # The signed app, not pkgs.espanso. Merges with the casks the other rooms
  # declare (nix-darwin concatenates homebrew.casks across modules).
  homebrew.casks = [ "espanso" ];

  # A module function so the inner `lib` is home-manager's (carries `lib.hm`);
  # the outer `lib` above is plain nixpkgs lib and has no `.hm`.
  home-manager.users.${username} =
    { lib, ... }:
    {
      home.file = {
        # show_icon parity with the old setup (no menu-bar glyph).
        ".config/espanso/config/default.yml".text = "show_icon: false\n";
        ".config/espanso/match/default.yml".text = matchesYaml;
      };

      # Register the app-bundle binary as the launchd service (stable identity)
      # and reload after a config change. Best-effort + idempotent: the cask is
      # installed by nix-darwin's Homebrew step, which can land after this on the
      # very first switch — if the app isn't there yet this no-ops, and the next
      # rebuild registers it. `service register` is safe to re-run. The one-time
      # Accessibility grant still has to be clicked by hand the first time
      # espanso starts (macOS won't let Nix self-grant it) — but only once,
      # thanks to the stable identity above.
      home.activation.espansoService = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
        if [ -x "${espanso}" ]; then
          $DRY_RUN_CMD "${espanso}" service register 2>/dev/null || true
          $DRY_RUN_CMD "${espanso}" restart 2>/dev/null \
            || $DRY_RUN_CMD "${espanso}" start 2>/dev/null || true
        fi
      '';
    };
}
